### PR TITLE
test etap 4 serverroulette v2

### PR DESCRIPTION
**Pull request by GZeed**
test

### CODE REVIEW

**Comment by wasadigi** [comment]
Thank you, but this is not the correct set of file. I only want your test for the protocol v2. Also, do NOT delete my test for V2.

**Comment by GZeed** [comment]
test v2

**Comment by GZeed** [comment]
thanks, I'm not sure

**Comment by GZeed** [comment]
I'm not sure, with this comit 6d25a4dfc489e84916e47a52587b365454ed8f61 I send to you only my test v2 pull request ?

**Pull request closed without merging**
